services:
  better-chatbot:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NO_HTTPS=1
    env_file:
      - .env
    networks:
      - better-chatbot-networks
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=better-chatbot
    # env_file:
    #   - .env
    networks:
      - better-chatbot-networks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  better-chatbot-networks:
    driver: bridge
